Branchone
juaryimami/Hello-Microverse pull request #1
Opened 2022-08-16 17:50 UTC by juaryimami

2022-08-16 17:52 UTC, juaryimami commented
merging

2022-08-16 18:32 UTC, Abenezer-Tilahun requested changes
Hi @juaryimami 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- [x] Good implementing for adding HTML and CSS file.

## Required Changes ♻️
_Check the comments under the review._

- [x] Set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config) and make sure that any files that are not relevant are ignored by git.
- [x] Add test.md file with the text "This file should be ignored by git" and make is actually ignored by git and is not present in your GitHub repository.
- [x] Add a .gitignore file. your gitignore file is empty.
- [ ] Add descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.
- [ ] Your Commit messages should be meaningful. please try to use meaningful commit messages in your future project.
- [ ] Your Pull Request should have a descriptive title telling you what changes are inside and should have a summary describing introduced changes in more detail.
- [ ] Your Branch should have a name of a feature or action (e.g. 'hello-microverse' or 'feature-hello').

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 18:32 UTC, Abenezer-Tilahun commented on A.html
> +</html>
- [ ] Please try to use standard markup language for Web pages and rename your Html file "index.html". For more information you can checkout this tutorial [here](https://www.w3schools.com/html/default.asp) for basic rules.

2022-08-16 18:32 UTC, Abenezer-Tilahun commented on A.css
> +};
- [ ] Good implementing styling the header with your favorite color. Please try to rename your .css file just like "style.css" and used to link in your index.html. For more information how to style page you can checkout [here](https://www.w3schools.com/html/html_css.asp)

2022-08-16 18:32 UTC, Abenezer-Tilahun commented on A.css
> +};
- [ ] Good implementing styling the header with your favorite color. Please try to rename your .css file just like "style.css" and used to link in your index.html. For more information how to style page you can checkout [here](https://www.w3schools.com/html/html_css.asp)

2022-08-16 18:40 UTC, juaryimami commented
Ok thank you

On Tue, 16 Aug 2022, 9:32 pm Abenezer-Tilahun, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @juaryimami <https://github.com/juaryimami>
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Highlights
>
>    - Good implementing for adding HTML and CSS file.
>
> Required Changes ♻️
>
> *Check the comments under the review.*
>
>    - Set up a linter for HTML and CSS
>    <https://github.com/microverseinc/linters-config> and make sure that
>    any files that are not relevant are ignored by git.
>    - Add test.md file with the text "This file should be ignored by git"
>    and make is actually ignored by git and is not present in your GitHub
>    repository.
>    - Add a .gitignore file. your gitignore file is empty.
>    - Add descriptive README file to your project - please use this
>    template <https://github.com/microverseinc/readme-template> but
>    remember to customize it to your project.
>    - Your Commit messages should be meaningful. please try to use
>    meaningful commit messages in your future project.
>    - Your Pull Request should have a descriptive title telling you what
>    changes are inside and should have a summary describing introduced changes
>    in more detail.
>    - Your Branch should have a name of a feature or action (e.g.
>    'hello-microverse' or 'feature-hello').
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In A.html
> <https://github.com/juaryimami/Hello-Microverse/pull/1#discussion_r947100533>
> :
>
> > +<html>
>
> +    <head>
>
> +
>
> +    </head>
>
> +    <body>
>
> +        <h1>
>
> +            Hello Microverse
>
> +        </h1>
>
> +    </body>
>
> +</html>
>
>
>
>    - Please try to use standard markup language for Web pages and rename
>    your Html file "index.html". For more information you can checkout this
>    tutorial here <https://www.w3schools.com/html/default.asp> for basic
>    rules.
>
> ------------------------------
>
> In A.css
> <https://github.com/juaryimami/Hello-Microverse/pull/1#discussion_r947105003>
> :
>
> > +h1{
>
> +    color: brown;
>
> +};
>
>
>
>    - Good implementing styling the header with your favorite color.
>    Please try to rename your .css file just like "style.css" and used to link
>    in your index.html. For more information how to style page you can checkout
>    here <https://www.w3schools.com/html/html_css.asp>
>
> ------------------------------
>
> In A.css
> <https://github.com/juaryimami/Hello-Microverse/pull/1#discussion_r947105233>
> :
>
> > +h1{
>
> +    color: brown;
>
> +};
>
>
>
>    - Good implementing styling the header with your favorite color.
>    Please try to rename your .css file just like "style.css" and used to link
>    in your index.html. For more information how to style page you can checkout
>    here <https://www.w3schools.com/html/html_css.asp>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/juaryimami/Hello-Microverse/pull/1#pullrequestreview-1074566888>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALX7MXTA6OILCDAJPPRREGTVZPND7ANCNFSM56WWOPEQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-16 21:12 UTC, merged

2022-08-16 22:31 UTC, bobb-Rob reviewed
Hi @juaryimami , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 22:31 UTC, bobb-Rob commented on A.css
> +};
Hi @juaryimami,

I understand that this is your first project in microverse and perhaps you are getting familiar with how projects are being reviewed. Kindly note the following:

- [ ] Please do not merge any pull request that has not been approved. Instead of merging, you should implement the changes requested by the previous reviewer. before you re-submit for re-review. 

- [ ] As requested by the previous reviewer, please consider renaming your CSS file to something more descriptive.

2022-08-16 22:31 UTC, bobb-Rob commented on README.md
- [ ] [OPTIONAL] It is best practice to give a detailed and concise description of your project under the description section in the README file.  In subsequent projects, please always endeavor to describe your project very well.

2022-08-16 22:31 UTC, bobb-Rob commented on README.md
- [ ] [OPTIONAL] As is expected of you in the requirement, always ensure you edit the README Template to better represent your projects. All sections that concern your project should be completed carefully.  

Please visit [this repo](https://github.com/bobb-Rob/watch-movie-tv-show-app) and see how your README  should be edited to fit your project.

The Author section should contain your name and social media handles as well as your GitHub link

2022-08-16 22:31 UTC, bobb-Rob commented on .stylelintrc
> +    }
- [ ] This linter file will not work as expected because its content is not correct. Kindly [visit the linter repo](https://github.com/microverseinc/linters-config/blob/master/html-css/.stylelintrc.json) and copy the right code into this file.

2022-08-16 22:31 UTC, bobb-Rob commented on .gitignore
> +*.iso
- [ ] [OPTIONAL] This `.gitignore` file should have _"node_modules/"_  and _"test.md"_ file in it. This will ensure you do commit the _"node_modules/"_ folder to git as this file can be very large as a result prolong y your push command, hence we do not want it in git. [See Why you don't have to commit node_modules folder](https://dev.to/grawl/why-you-dont-have-to-commit-nodemodules-folder-33nm)

2022-08-17 04:24 UTC, juaryimami commented
Thanks a lot.

On Wed, 17 Aug 2022, 1:32 am Robertson Arthur, ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Hi @juaryimami <https://github.com/juaryimami> ,
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
>
> <https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In A.css
> <https://github.com/juaryimami/Hello-Microverse/pull/1#discussion_r947286004>
> :
>
> > +h1{
>
> +    color: brown;
>
> +};
>
>
> Hi @juaryimami <https://github.com/juaryimami>,
>
> I understand that this is your first project in microverse and perhaps you
> are getting familiar with how projects are being reviewed. Kindly note the
> following:
>
>    -
>
>    Please do not merge any pull request that has not been approved.
>    Instead of merging, you should implement the changes requested by the
>    previous reviewer. before you re-submit for re-review.
>    -
>
>    As requested by the previous reviewer, please consider renaming your
>    CSS file to something more descriptive.
>
> ------------------------------
>
> In README.md
> <https://github.com/juaryimami/Hello-Microverse/pull/1#discussion_r947287780>
> :
>
> >
>
>  > Description the project.
>
>
>
>
>
>
>
>    - [OPTIONAL] It is best practice to give a detailed and concise
>    description of your project under the description section in the README
>    file. In subsequent projects, please always endeavor to describe your
>    project very well.
>
> ------------------------------
>
> In README.md
> <https://github.com/juaryimami/Hello-Microverse/pull/1#discussion_r947291878>
> :
>
> > -
>
> -[Live Demo Link](https://livedemo.com)
>
> -
>
> -
>
> -## Getting Started
>
> -
>
> -**This is an example of how you may give instructions on setting up your project locally.**
>
> -**Modify this file to match your project, remove sections that don't apply. For example: delete the testing section if the currect project doesn't require testing.**
>
> -
>
> -
>
> -To get a local copy up and running follow these simple example steps.
>
> +- HTML CSS
>
> +- Visual Studio Code
>
> +- git github
>
>
>
>  ### Prerequisites
>
>
>
>
>
>    - [OPTIONAL] As is expected of you in the requirement, always ensure
>    you edit the README Template to better represent your projects. All
>    sections that concern your project should be completed carefully.
>
> Please visit this repo
> <https://github.com/bobb-Rob/watch-movie-tv-show-app> and see how your
> README should be edited to fit your project.
>
> The Author section should contain your name and social media handles as
> well as your GitHub link
> ------------------------------
>
> In .stylelintrc
> <https://github.com/juaryimami/Hello-Microverse/pull/1#discussion_r947295997>
> :
>
> > +
>
> +    rules:{
>
> +
>
> +		'annotation-no-unknown'; true;
>
> +		
>
> +    }
>
>
>
>    - This linter file will not work as expected because its content is
>    not correct. Kindly visit the linter repo
>    <https://github.com/microverseinc/linters-config/blob/master/html-css/.stylelintrc.json>
>    and copy the right code into this file.
>
> ------------------------------
>
> In .gitignore
> <https://github.com/juaryimami/Hello-Microverse/pull/1#discussion_r947299808>
> :
>
> > +.idea
>
> +*.md
>
> +*.rar
>
> +*.zip
>
> +*.rar
>
> +*.log
>
> +*.iso
>
>
>
>    - [OPTIONAL] This .gitignore file should have *"node_modules/"* and
>    *"test.md"* file in it. This will ensure you do commit the
>    *"node_modules/"* folder to git as this file can be very large as a
>    result prolong y your push command, hence we do not want it in git. See
>    Why you don't have to commit node_modules folder
>    <https://dev.to/grawl/why-you-dont-have-to-commit-nodemodules-folder-33nm>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/juaryimami/Hello-Microverse/pull/1#pullrequestreview-1074825468>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALX7MXVEAYREGFWUEJLPEJLVZQJGRANCNFSM56WWOPEQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>